services:
  - type: web
    name: pcos-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO_ID
        value: SIYAM1809/pcos-clinical-ensemble
    plan: free
